resume:
pretrain:
seed: 1024
data:
    dataset: k400
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 8
    workers: 4
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg'
    train_root: '/bpfs/v2_mnt/VIS/test/k400/train_320_frames'
    train_list: 'lists/k400/kinetics_rgb_train_se320.txt'
    val_root: /bpfs/v2_mnt/VIS/test/k400/kinetics_400_val_320_opencv
    val_list: lists/k400/kinetics_rgb_val_se320.txt
    label_list: 'lists/kinetics_400_labels.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 2 #2
        M: 9  #9
    random_shift: True
    shot: 2
network:
    arch: ViT-L/14  #ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_k400
    sim_header: None  
    drop: 0         
solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-5
    lr_warmup_step: 5
    weight_decay: 0.2
    loss_type: CE
    evaluate: False
    clip_ratio: 0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 1